format = """
[â–‘â–’â–“](#d2a3a3)\
[ ïŒƒ ](bg:#d2a3a3 fg:#0c0909)\
[î‚´](bg:#f07575 fg:#d2a3a3)\
$directory\
[î‚´](fg:#f07575 bg:#603939)\
$git_branch\
$git_status\
[î‚´](fg:#603939 bg:#362121)\
$nodejs\
$rust\
$golang\
$php\
[î‚´](fg:#362121 bg:#301d1d)\
$time\
[î‚´ ](fg:#301d1d)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#f07575"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ğŸ—‚"
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#603939"
format = '[[ $symbol $branch ](fg:#f07575 bg:#603939)]($style)'

[git_status]
style = "bg:#603939"
format = '[[($all_status$ahead_behind )](fg:#f07575 bg:#603939)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#362121"
format = '[[ $symbol ($version) ](fg:#f07575 bg:#603939)]($style)'

[rust]
symbol = "î¨"
style = "bg:#362121"
format = '[[ $symbol ($version) ](fg:#f07575 bg:#603939)]($style)'

[golang]
symbol = "ï³‘"
style = "bg:#362121"
format = '[[ $symbol ($version) ](fg:#f07575 bg:#603939)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#362121"
format = '[[ $symbol ($version) ](fg:#f07575 bg:#603939)]($style)'

[time]
disabled = true
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#301d1d"
format = '[[ ïº $time ](fg:#caa0a0 bg:#301d1d)]($style)'
