format = """
[â–‘â–’â–“](#d29db0)\
[ ïŒƒ ](bg:#d29db0 fg:#090c0b)\
[î‚´](bg:#f07185 fg:#d29db0)\
$directory\
[î‚´](fg:#f07185 bg:#603745)\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
[î‚´](fg:#362124 bg:#301e1d)\
$time\
[î‚´ ](fg:#301e1d)\
\n$character"""

[directory]
style = "fg:#e4e3e5 bg:#f07185"
format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents/Code" = "{}"
"Documents" = "ğŸ—‚"
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#603745"
format = '[[ $symbol $branch ](fg:#f07185 bg:#603745)]($style)'

[git_status]
style = "bg:#603745"
format = '[[($all_status$ahead_behind )](fg:#f07185 bg:#603745)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#362124"
format = '[[ $symbol ($version) ](fg:#f07185 bg:#603745)]($style)'

[rust]
symbol = "ğŸ¦€"
style = "bg:#362124"
format = '[[ $symbol ($version) ](fg:#f07185 bg:#603745)]($style)'

[golang]
symbol = "ğŸ¹ "
style = "bg:#362124"
format = '[[ $symbol ($version) ](fg:#f07185 bg:#603745)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#362124"
format = '[[ $symbol ($version) ](fg:#f07185 bg:#603745)]($style)'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#301e1d"
format = '[[ ïº $time ](fg:#caa0a8 bg:#301e1d)]($style)'
