format = """
[â–‘â–’â–“](#baa2d2)\
[ ïŒƒ ](bg:#baa2d2 fg:#0a090c)\
[î‚´](bg:#b274f0 fg:#baa2d2)\
$directory\
[î‚´](fg:#b274f0 bg:#4c3860)\
$git_branch\
$git_status\
[î‚´](fg:#4c3860 bg:#2b2136)\
$nodejs\
$rust\
$golang\
$php\
[î‚´](fg:#2b2136 bg:#261d30)\
$time\
[î‚´ ](fg:#261d30)\
\n$character"""

[directory]
style = "fg:#e4e5e3 bg:#b274f0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ğŸ—‚"
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#4c3860"
format = '[[ $symbol $branch ](fg:#b274f0 bg:#4c3860)]($style)'

[git_status]
style = "bg:#4c3860"
format = '[[($all_status$ahead_behind )](fg:#b274f0 bg:#4c3860)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#2b2136"
format = '[[ $symbol ($version) ](fg:#b274f0 bg:#4c3860)]($style)'

[rust]
symbol = "î¨"
style = "bg:#2b2136"
format = '[[ $symbol ($version) ](fg:#b274f0 bg:#4c3860)]($style)'

[golang]
symbol = "ï³‘"
style = "bg:#2b2136"
format = '[[ $symbol ($version) ](fg:#b274f0 bg:#4c3860)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#2b2136"
format = '[[ $symbol ($version) ](fg:#b274f0 bg:#4c3860)]($style)'

[time]
disabled = true
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#261d30"
format = '[[ ïº $time ](fg:#b5a0ca bg:#261d30)]($style)'
